stages:
  - build

before_script:
  - apt-get update -y
  - apt-get install -y cmake
  - apt-get install -y build-essential
  - apt-get install -y liblua5.2-dev
  - apt-get install -y libgmp3-dev 
  - apt-get install -y libmysqlclient-dev
  - apt-get install -y libboost-system-dev
  - apt-get install -y libboost-iostreams-dev
  - apt-get install -y libpugixml-dev
  - apt-get install -y libcrypto++-dev

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make