version: "3.7"

services:
  database:
    container_name: otxserver-database
    restart: unless-stopped
    image: mysql:5.7
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user@123
      - MYSQL_DATABASE=global
      - MYSQL_ROOT_PASSWORD=root@123
    ports:
      - "3306:3306"
    volumes:
      - otx-mysql:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    networks:
      network:
        ipv4_address: 172.27.1.1

  otserv:
    depends_on:
      - database
    links:
      - database
    container_name: otxserver
    build: .
    ports:
      - "7171:7171"
      - "7172:7172"
      - "7173:7173"
    volumes:
      - ./data:/app/data
    networks:
      network:
        ipv4_address: 172.27.1.2

volumes:
  otx-mysql: {}

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
